<Project>

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <OutputPath>..\bin\Win64_Shipping_Client\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=.</PathMap>
    <DeterministicSourcePaths>true</DeterministicSourcePaths>

    <BannerlordDir Condition=" '$(BannerlordDir)' == '' AND '$(BANNERLORD_DIR)' != '' ">$(BANNERLORD_DIR)\</BannerlordDir>
    <BannerlordDir Condition=" '$(BannerlordDir)' == '' AND Exists('C:\Program Files (x86)\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.Core.dll') ">C:\Program Files (x86)\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\</BannerlordDir>
    <GameBinDir>$(BannerlordDir)bin\Win64_Shipping_Client\</GameBinDir>
    <TORBinDir>$(BannerlordDir)Modules\TOR_Core\bin\Win64_Shipping_Client\</TORBinDir>
    <HarmonyBinDir>$(BannerlordDir)Modules\Bannerlord.Harmony\bin\Win64_Shipping_Client\</HarmonyBinDir>
    <SandBoxBinDir>$(BannerlordDir)Modules\SandBox\bin\Win64_Shipping_Client\</SandBoxBinDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.Core" HintPath="$(GameBinDir)TaleWorlds.Core.dll" Private="false" />
    <Reference Include="TaleWorlds.Core.ViewModelCollection" HintPath="$(GameBinDir)TaleWorlds.Core.ViewModelCollection.dll" Private="false" />
    <Reference Include="TaleWorlds.Library" HintPath="$(GameBinDir)TaleWorlds.Library.dll" Private="false" />
    <Reference Include="TaleWorlds.MountAndBlade" HintPath="$(GameBinDir)TaleWorlds.MountAndBlade.dll" Private="false" />
    <Reference Include="TaleWorlds.ObjectSystem" HintPath="$(GameBinDir)TaleWorlds.ObjectSystem.dll" Private="false" />
    <Reference Include="TaleWorlds.DotNet" HintPath="$(GameBinDir)TaleWorlds.DotNet.dll" Private="false" />
    <Reference Include="TaleWorlds.Engine" HintPath="$(GameBinDir)TaleWorlds.Engine.dll" Private="false" />
    <Reference Include="TaleWorlds.Localization" HintPath="$(GameBinDir)TaleWorlds.Localization.dll" Private="false" />
    <Reference Include="TaleWorlds.CampaignSystem" HintPath="$(GameBinDir)TaleWorlds.CampaignSystem.dll" Private="false" />
    <Reference Include="TaleWorlds.ModuleManager" HintPath="$(GameBinDir)TaleWorlds.ModuleManager.dll" Private="false" />
    <Reference Include="TOR_Core" HintPath="$(TORBinDir)TOR_Core.dll" Private="false" />
    <Reference Include="0Harmony" HintPath="$(HarmonyBinDir)0Harmony.dll" Private="false" />
  </ItemGroup>

</Project>
