<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>TORWaywatcherOverhaul</AssemblyName>
    <RootNamespace>TORWaywatcherOverhaul</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SandBox" HintPath="$(SandBoxBinDir)SandBox.dll" Private="false" />
  </ItemGroup>

</Project>
